spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/banquanao
    username: root
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
jwt:
  key: ${JWT_KEY}
  access-token-expiration: 36000000
  refresh-token-expiration: 86400000
